### ISSUE TITLE
TypeError: Path must be a string. Received undefined

### ISSUE THREAD

**Issue by ChiaJune** [jpavon/react-scripts-ts#2]
run command `yarn start` after `yarn eject` get the error：
``` bash
path.js:28
    throw new TypeError('Path must be a string. Received ' + inspect(path));
    ^

TypeError: Path must be a string. Received undefined
    at assertPath (path.js:28:11)
    at Object.resolve (path.js:211:7)
    at Function.findConfig (C:\Users\xxx\Desktop\my-app\node_modules\react-dev-utils\node_modules\browserslist\node.js:212:17)
    at checkBrowsers (C:\Users\xxx\Desktop\my-app\node_modules\react-dev-utils\browsersHelper.js:24:32)
    at Object.<anonymous> (C:\Users\xxx\Desktop\my-app\scripts\start.js:65:1)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by jpavon** [comment]
@ChiaJune I didn't test the eject command in this project, the best you can do is fork the project and use modify it from there, you can add the #1 in your fork
